### ISSUE TITLE
keyboard shortcuts possible?

### ISSUE THREAD

**Issue by jkitchin** [jmshea/jupytercards#3]
Any idea how hard it would be to add keyboard shortcuts, e.g. space to flip card, and j/k for previous/next card?

**Comment by jmshea** [comment]
I've been meaning to do that. I'll give it a go and get back to you.

**Comment by jmshea** [comment]
@jkitchin Can you give the latest version (2.0.0rc1) a try? If you are installing via pip, do 

`pip install  jupytercards==2.0.0rc1`

Then restart your Jupyter kernel and run a cell with JupyterCards again. 

The following should work:
* space to flip card over
* j, Enter, or right arrow to move to next card

I don't have an animation for going back through the deck yet, so that is on hold.

Please let me know if this is working for you.  I think there is still sometimes a bit of weird behavior if this is compiled into a Jupyter Book.

**Comment by jkitchin** [comment]
This seems to work great!
